spring.application.name=delivery-ms-bff
server.port=8079

# urls microsservicos
url.delivery.ms.user=http://localhost:8080
url.delivery.ms.customer=http://localhost:8081
url.delivery.ms.payment=http://localhost:8082